// Central question bank used by both the Question Bank page
// and (optionally) the interview question generator.

export const QUESTION_BANK = {
  general: {
    key: "general",
    title: "General / Behavioral",
    description:
      "Most common HR & behavioral questions that appear in interviews across roles.",
    questions: [
      "Tell me about yourself.",
      "What are your strengths?",
      "What are your weaknesses?",
      "Why are you interested in this role?",
      "Where do you see yourself in 5 years?",
      "Why do you want to work at this company?",
      "What is your greatest professional achievement?",
      "Tell me about a challenge or conflict you've faced at work, and how you dealt with it.",
      "Tell me about a time you demonstrated leadership skills.",
      "What's a time you disagreed with a decision that was made at work?",
      "Tell me about a time you made a mistake.",
      "Tell me about a time you failed.",
      "Why should we hire you?",
      "What are you looking for in a new position?",
      "What type of work environment do you prefer?",
      "What's your management style?",
      "What are your salary expectations?",
      "How would your boss and co-workers describe you?",
      "How do you deal with pressure or stressful situations?",
      "What are your hobbies?",
      "What motivates you?",
      "What are your pet peeves?",
      "How do you like to be managed?",
      "Do you have any questions for us?",
      "What do you like to do outside of work?",
      "Describe a time you had to learn a new skill quickly.",
      "How do you prioritize your work?",
      "What are you passionate about?",
      "What do you do to ensure quality in your work?",
      "Tell me about a time you had to work with a difficult person.",
      "What does 'leadership' mean to you?",
      "If you were starting a company tomorrow, what would be its top three values?",
      "How do you handle feedback you disagree with?",
      "Describe your ideal work-life balance.",
      "What's a professional skill you're currently working on?",
      "Tell me about a time you had to persuade someone to see your point of view.",
      "How do you stay organized?",
      "What's the most important thing you've learned in your career so far?",
      "Describe a situation where you went above and beyond your job responsibilities.",
      "What are some of your long-term career goals?",
      "How do you adapt to change?",
      "What kind of company culture are you looking for?",
      "If you could have any job in the world, what would it be and why?",
      "What are you most proud of in your personal life?",
      "How do you define success?",
      "Tell me something about you that isn't on your resume.",
      "Describe a time you had to make an unpopular decision.",
      "What is your preferred method of communication?",
      "How do you deal with ambiguity?",
      "What are your thoughts on remote work versus in-office work?",
      "Tell me about a time you had to give someone difficult feedback.",
      "How do you build rapport with colleagues?",
      "What's one thing you would change about your last role?",
      "What does it mean to be a team player?",
      "How do you keep yourself motivated during challenging projects?",
      "What is your greatest accomplishment?"
    ]
  },

  dataAnalyst: {
    key: "dataAnalyst",
    title: "Data Analyst / BI / GCP Data",
    description:
      "Conceptual, SQL, BI, and Google Cloud–oriented questions for data & analytics roles.",
    questions: [
      "What is the difference between data analysis and data mining?",
      "What are the different types of data?",
      "How do you handle missing or incomplete data?",
      "What are some common data analysis tools?",
      "How do you communicate your findings to a non-technical audience?",
      "Can you describe a time when you used data to solve a problem?",
      "What is your experience with data visualization?",
      "What are some common challenges you face as a data analyst?",
      "How do you stay up-to-date on the latest data analysis trends?",
      "What are your thoughts on the future of data analysis?",
      "What is data wrangling?",
      "What are some of the most common biases that can occur in data analysis?",
      "What are some of the ethical considerations that data analysts need to be aware of?",
      "What is A/B testing?",
      "What is a cohort analysis?",
      "What is a funnel analysis?",
      "What is a regression analysis?",
      "What is a time series analysis?",
      "What is a decision tree?",
      "What is a neural network?",
      "How would you use data to improve a product or service?",
      "How would you use data to make a business decision?",
      "How would you use data to identify a new market opportunity?",
      "How would you use data to track the performance of a marketing campaign?",
      "How would you use data to measure the success of a new product launch?",
      "How would you use data to understand customer behavior?",
      "Tell me about a time you had to work with a difficult stakeholder. How did you manage the situation?",
      "Describe a project where you had to work with a large and complex dataset. What were the challenges and how did you overcome them?",
      "Tell me about a time you made a mistake in your analysis. How did you identify and correct it?",
      "How do you ensure the quality and accuracy of your data?",
      "What are your strengths and weaknesses as a data analyst?",
      "Describe the difference between data that is high-cardinality and data that is low-cardinality. Why is this distinction important?",
      "Tell me about a time when you had to make a presentation to a non-technical audience. How did you prepare? What was the outcome?",
      "How would you explain a p-value to a business stakeholder?",
      "What's the difference between a bar chart and a histogram?",
      "Explain the different types of joins in SQL.",
      "What are window functions in SQL and when would you use them?",
      "What is the difference between structured and unstructured data?",
      "What's a method you could use to determine if an outlier is a 'bad' data point?",
      "What is the difference between an observational and an experimental study?",
      "How do you approach data storytelling?",
      "What is the difference between Business Intelligence and Data Analytics?",
      "Describe the ETL process (Extract, Transform, Load).",
      "What are some common BI tools you have used?",
      "What is a data warehouse and how does it differ from a database?",
      "What is the difference between a star schema and a snowflake schema?",
      "How would you design a dashboard for a sales team?",
      "Tell me about a time you used BI to provide a key insight that drove a business decision.",
      "What are KPIs and how do you define them for a business?",
      "What is OLAP (Online Analytical Processing)?",
      "How do you ensure data quality in a BI system?",
      "How does BigQuery work and what are its key features?",
      "Describe a scenario where you would use Dataflow.",
      "What is the difference between Bigtable and BigQuery?",
      "How would you build a data pipeline on Google Cloud Platform?",
      "Explain the role of Pub/Sub in a real-time analytics architecture.",
      "What are some best practices for managing costs in BigQuery?",
      "How do you handle data security and access control in Google Cloud Storage and BigQuery?",
      "Describe your experience with Looker or Looker Studio for data visualization on GCP.",
      "What is Dataproc and when would you use it over other services like Dataflow?",
      "How can you use AI Platform Notebooks for data exploration and model development on GCP?",
      "Case Study: Our user engagement for a specific feature has dropped by 15% in the last month. How would you investigate the cause?",
      "What is the difference between leading and lagging indicators? Give an example of each for a subscription-based business.",
      "You are given a dataset of customer transactions. How would you identify the most valuable customers?",
      "Explain the concept of statistical significance. Why is it important in business decision-making?",
      "How would you measure the ROI of a marketing campaign?",
      "Describe a scenario where a time-series forecasting model would be useful.",
      "What are the pros and cons of using SQL versus a programmatic language like Python for data analysis?",
      "How do you approach data validation and cleaning?",
      "Case Study: We are considering launching a new pricing model. What data would you need to analyze, and how would you structure your analysis to support this decision?",
      "Explain the concept of a 'data dictionary' and why it's a critical component of data governance.",
      "How would you approach a project to segment our customer base? What variables would you consider?",
      "What is the difference between a primary key and a foreign key in a relational database?",
      "You have discovered a data anomaly that could impact a recent report sent to senior leadership. What are your immediate next steps?",
      "Describe a situation where data visualization led to a misleading conclusion. How could this have been avoided?",
      "What is your process for documenting your data analysis projects to ensure reproducibility?"
    ]
  },

  itSupport: {
    key: "itSupport",
    title: "IT Support / Helpdesk",
    description:
      "Troubleshooting, networking, Windows, and user-support focused questions.",
    questions: [
      "Walk me through the troubleshooting steps you would take if a user said their computer was running slow.",
      "A user is unable to connect to the office Wi-Fi. How would you help them?",
      "What is the difference between a switch, a router, and a hub?",
      "How would you explain what a 'firewall' is to a non-technical person?",
      "A user reports they've received a suspicious email. What are your immediate instructions to them?",
      "What is Active Directory and what is it used for?",
      "How do you handle a situation where a user is frustrated and angry because their computer isn't working?",
      "What is the command to find a computer's IP address on Windows? What about on a Mac?",
      "Describe the process of setting up a new employee's computer.",
      "What is the difference between RAM and a hard drive?",
      "How do you stay up-to-date with the latest technology trends and security threats?",
      "A user can't print to a network printer. What are the potential causes?",
      "What are some common forms of malware and how do you prevent them?",
      "What is the purpose of DNS?",
      "Explain the difference between HTTP and HTTPS.",
      "What is a VPN and why would a company use one?",
      "How would you recover data from a corrupted hard drive?",
      "Describe your experience with ticketing systems.",
      "What is the principle of least privilege?",
      "How would you handle a request for a software installation that is not on the approved list?",
      "A user's application keeps crashing. What information do you need to gather from them to start troubleshooting?",
      "What is 'safe mode' in an operating system, and when would you use it?",
      "How do you manage software licenses for a team or organization?",
      "What is a 'blue screen of death' (BSOD) and what are some common causes?",
      "Describe the difference between a full backup, an incremental backup, and a differential backup.",
      "What is DHCP and what role does it play on a network?",
      "How would you handle a situation where you suspect a user's account has been compromised?",
      "What are Group Policies in a Windows environment?",
      "Explain what an SLA (Service Level Agreement) is in the context of IT support.",
      "How do you document your troubleshooting steps and resolutions?",
      "A user needs remote assistance. What tools and procedures would you use?",
      "What is the difference between a local user account and a domain user account?",
      "How would you troubleshoot a computer that won't turn on at all?",
      "What is the purpose of the event viewer in Windows?",
      "Describe your experience with mobile device management (MDM) solutions.",
      "How do you prioritize support tickets when multiple users report urgent issues simultaneously?",
      "What are the benefits of using a knowledge base for IT support?",
      "A user has forgotten their password. What is the secure procedure to help them regain access?",
      "What are file permissions, and why are they important?",
      "How would you set up a new network printer for an office?",
      "Case Study: A department-wide outage of a critical application has just been reported. What are your initial steps in the first 15 minutes?",
      "Explain the OSI model and how it relates to troubleshooting network issues.",
      "What is 'phishing' and how can you educate users to recognize it?",
      "How would you handle an IT support request that is outside your area of expertise?",
      "What is RAID? Explain the difference between RAID 0, RAID 1, and RAID 5.",
      "Describe a time you had to create documentation for a technical process. Who was the audience and what was the outcome?",
      "What are some common command-line tools you use for network diagnostics?",
      "What is a proxy server and why might a company use one?",
      "How do you ensure you are providing excellent customer service in an IT support role?",
      "Case Study: You receive a ticket that a VIP executive's laptop is not working right before a major presentation. How do you approach this situation?"
    ]
  },

  projectManagement: {
    key: "projectManagement",
    title: "Project Management",
    description:
      "End-to-end project lifecycle, risk, stakeholders, Agile vs Waterfall and leadership.",
    questions: [
      "Describe a time when a project you were managing was in jeopardy. What did you do to get it back on track?",
      "What is your ideal project?",
      "How do you decide which projects to prioritize?",
      "Tell me about a time you had to manage a project with a team of people who had very different personalities.",
      "Tell me about a time you had to manage a project with a very tight deadline.",
      "How do you manage stakeholders who have competing interests?",
      "What are some of the most common project management methodologies?",
      "What are the different stages of a project life cycle?",
      "What is a project charter and what should it include?",
      "What is a work breakdown structure (WBS) and how is it used?",
      "What is a Gantt chart and what is it used for?",
      "What is a critical path and how is it determined?",
      "What is risk management and what are some of the most common risks that projects face?",
      "How do you track and report on project progress?",
      "How do you handle scope creep?",
      "How do you close out a project?",
      "What are some of the most important skills for a project manager to have?",
      "What are some of the biggest challenges that project managers face?",
      "What is the difference between Agile and Waterfall project management?",
      "How do you define the scope of a project?",
      "What is a RACI chart and how do you use it?",
      "Describe your experience with budget management for a project.",
      "How do you ensure effective communication within your project team?",
      "Tell me about a time you had to manage a difficult stakeholder. How did you handle it?",
      "What is a change control process, and why is it important?",
      "How do you conduct a post-mortem or lessons learned session after a project is completed?",
      "What project management software are you familiar with?",
      "How do you motivate a team, especially during challenging phases of a project?",
      "What are project milestones, and how do you use them?",
      "Explain the concept of 'earned value management' (EVM).",
      "How do you handle resource allocation for a project?",
      "Describe a time when you had to say 'no' to a stakeholder's request. How did you approach the conversation?",
      "What is a statement of work (SOW)?",
      "How do you measure project success beyond 'on time and on budget'?",
      "What is your approach to quality management in a project?",
      "Case Study: Your project is three months from its deadline, and a key team member has just resigned. What steps do you take to mitigate the impact?",
      "How do you foster a collaborative environment within your project team?",
      "What is a risk register, and what kind of information does it contain?",
      "How do you handle dependencies between different projects or teams?",
      "Describe a complex project you managed. What made it complex, and how did you navigate that complexity?",
      "What is the difference between a project manager and a program manager?",
      "Case Study: You've been assigned to a project that is already failing. What is your 30-60-90 day plan to turn it around?"
    ]
  },

  softwareEngineering: {
    key: "softwareEngineering",
    title: "Software Engineering & DSA",
    description:
      "Core CS, system design, and LeetCode-style coding questions for SWE roles.",
    questions: [
      "What is the difference between a process and a thread?",
      "Describe the software development life cycle (SDLC).",
      "What are the key principles of Agile development?",
      "Explain the difference between coupling and cohesion.",
      "What is a RESTful API? What are the main principles of REST?",
      "What are the differences between an array and a linked list?",
      "Describe a hash table. What are its advantages and disadvantages?",
      "What is object-oriented programming (OOP)? Explain its core concepts.",
      "What is the difference between inheritance and composition?",
      "What is polymorphism?",
      "Explain the SOLID principles of object-oriented design.",
      "What is a design pattern? Give an example of one you have used.",
      "What is version control and why is it important?",
      "What is the difference between Git and GitHub?",
      "What is database normalization? Why is it important?",
      "Explain the concept of Big O notation and why it matters.",
      "What are the time and space complexities of a binary search algorithm?",
      "How would you design a system like a URL shortener?",
      "Tell me about a challenging technical problem you solved.",
      "How do you ensure the quality of your code?",
      "What is the difference between unit tests, integration tests, and end-to-end tests?",
      "What is continuous integration and continuous delivery (CI/CD)?",
      "Explain the concept of 'technical debt' and how you manage it.",
      "What is the difference between a microservices architecture and a monolithic architecture?",
      "What is containerization, and what are the benefits of using tools like Docker?",
      "Explain how an event loop works in JavaScript.",
      "What are some common security vulnerabilities in web applications, and how do you prevent them?",
      "What is the difference between SQL and NoSQL databases? Give an example of when you would use each.",
      "How do you handle error logging and monitoring in a production application?",
      "How does HTTPS work?",
      "What are some strategies for scaling a web application?",
      "What is dependency injection?",
      "What is the role of a load balancer?",
      "Explain the concept of 'idempotency' in the context of APIs.",
      "How would you design a system that needs to process a large number of asynchronous jobs?",

      // LeetCode-style questions
      "Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.",
      "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.",
      "Merge two sorted linked lists and return it as a new sorted list.",
      "Given an integer array nums, find the contiguous subarray which has the largest sum and return its sum.",
      "Given a binary tree, determine if it is a valid binary search tree (BST).",
      "You want to maximize your profit by choosing a single day to buy one stock and a different day to sell. Return the maximum profit.",
      "Implement an LRU (Least Recently Used) Cache. It should support get and put operations.",
      "Given a string s, find the length of the longest substring without repeating characters.",
      "Given an m x n 2D binary grid of '1's and '0's, return the number of islands.",
      "Given the head of a singly linked list, reverse the list, and return the reversed list.",
      "Given an array of strings strs, group the anagrams together.",
      "Implement the atoi function, which converts a string to a 32-bit signed integer.",
      "Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.",
      "You are given an integer array height. Find two lines that together with the x-axis form a container that holds the most water."
    ]
  },

  dataScience: {
    key: "dataScience",
    title: "Data Science / ML",
    description:
      "Statistics, ML concepts, and end-to-end data science workflow questions.",
    questions: [
      "What is the difference between supervised and unsupervised learning?",
      "Explain the bias-variance tradeoff.",
      "What is a confusion matrix? Explain precision, recall, and F1-score.",
      "What are Type I and Type II errors?",
      "What is the difference between correlation and causation?",
      "How do you handle missing or corrupted data in a dataset?",
      "What is cross-validation? Why is it useful and what are different methods?",
      "Explain the steps in making a decision tree.",
      "What is logistic regression? When is it used?",
      "What is the difference between K-means and KNN (K-Nearest Neighbors)?",
      "What is dimensionality reduction? Name two methods.",
      "Explain what regularization is and why it is useful.",
      "What is the ROC curve and AUC?",
      "How would you choose a suitable metric for evaluating a classification model?",
      "What is the difference between a data scientist, a data analyst, and a data engineer?",
      "Describe a data science project you have worked on from start to finish.",
      "How do you deal with an imbalanced dataset?",
      "What is p-value and what does it signify?",
      "Explain Principal Component Analysis (PCA).",
      "What is the difference between a generative and a discriminative model?",
      "What is feature engineering? Give an example.",
      "What is the 'curse of dimensionality'?",
      "What are some of your favorite Python libraries for data science?",
      "What is deep learning, and how does it differ from traditional machine learning?",
      "Explain what a neural network is.",
      "What is backpropagation?",
      "How would you build a recommendation system for a movie streaming service?",
      "What is overfitting and how can you prevent it?",
      "Describe a time you had to work with a very large dataset. What tools and techniques did you use?",
      "What is natural language processing (NLP)? Give an example of an NLP task.",
      "Explain what a gradient boosting model is.",
      "What are some different types of clustering algorithms?",
      "How do you deploy a machine learning model into production?",
      "What is the difference between batch learning and online learning?",
      "How do you monitor the performance of a model once it is in production?",
      "What is transfer learning?",
      "Case Study: Our e-commerce platform wants to predict customer churn. What would be your approach to building a model for this?",
      "What is the difference between a random forest and a gradient boosting machine?",
      "What are some ways to handle categorical variables in a dataset?",
      "What is time-series forecasting? Name a model you would use for this.",
      "What are some ethical considerations you need to be aware of as a data scientist?",
      "Case Study: You are tasked with building a model to detect fraudulent credit card transactions. The dataset is highly imbalanced. How do you proceed?"
    ]
  },

  marketing: {
    key: "marketing",
    title: "Marketing & Growth",
    description:
      "Digital marketing, funnels, campaigns, and growth-focused questions.",
    questions: [
      "What is the marketing funnel and how has it evolved?",
      "Describe the difference between marketing and branding.",
      "How would you develop a marketing strategy for a new product?",
      "What are the most important metrics to track in a digital marketing campaign?",
      "Tell me about a successful marketing campaign you managed. What were the results?",
      "What's your experience with SEO and SEM?",
      "How do you approach content marketing?",
      "What are the key components of a successful social media strategy?",
      "How do you calculate Customer Lifetime Value (CLV)?",
      "Explain the concept of A/B testing in a marketing context.",
      "How do you stay up-to-date with the latest marketing trends and technologies?",
      "Describe a time you had to work with a tight marketing budget. What did you do?",
      "What is your experience with email marketing and marketing automation?",
      "How would you market our company to a new audience segment?",
      "What role does data analysis play in your marketing decisions?",
      "What is the difference between inbound and outbound marketing?",
      "What is a go-to-market (GTM) strategy?",
      "Describe your experience with paid advertising platforms like Google Ads or Facebook Ads.",
      "What is a content calendar and how do you use it?",
      "How do you measure brand awareness?",
      "What is influencer marketing, and when is it an effective strategy?",
      "Explain the concept of a 'marketing persona'.",
      "How do you use marketing analytics to drive strategy?",
      "What is your approach to competitor analysis?",
      "Case Study: Our user acquisition has been flat for the last quarter. What are some strategies you would explore to re-ignite growth?"
    ]
  },

  productManagement: {
    key: "productManagement",
    title: "Product Management",
    description:
      "Strategy, discovery, roadmap, and stakeholder-management questions.",
    questions: [
      "What is product management?",
      "What is your favorite product and how would you improve it?",
      "How do you decide what features to build next?",
      "Describe your process for developing a product roadmap.",
      "How do you prioritize features when you have limited resources?",
      "Tell me about a time you had to make a difficult product decision.",
      "How do you work with engineering, design, and marketing teams?",
      "How do you define and measure the success of a product?",
      "Tell me about a product you launched. What went well and what would you do differently?",
      "How do you gather and incorporate user feedback?",
      "What is the difference between a product manager and a project manager?",
      "Describe the product development lifecycle at your previous company.",
      "How do you determine product-market fit?",
      "What is a PRD (Product Requirements Document), and what are its key components?",
      "What are some prioritization frameworks you have used (e.g., RICE, MoSCoW)?",
      "How do you communicate your product vision to the team and the wider company?",
      "Case Study: Our user retention rate is declining. How would you investigate the problem and what steps would you take to address it?"
    ]
  },

  businessAnalyst: {
    key: "businessAnalyst",
    title: "Business Analyst",
    description:
      "Requirements, stakeholders, processes and business value focused questions.",
    questions: [
      "What is the role of a Business Analyst in a project?",
      "What are the key skills of a successful Business Analyst?",
      "Walk me through your process for gathering requirements from stakeholders.",
      "What is the difference between business requirements and functional requirements?",
      "What techniques do you use for requirements elicitation?",
      "How do you handle conflicting requirements from different stakeholders?",
      "What is a SWOT analysis and when would you use it?",
      "Explain what a use case is and how you create one.",
      "Describe your experience with creating process models (e.g., flowcharts, BPMN).",
      "How do you ensure that the developed solution meets the business needs?",
      "What is UAT (User Acceptance Testing) and what is your role in it?",
      "Tell me about a time you had to communicate a complex technical issue to a non-technical audience.",
      "How do you manage changes to requirements during a project?",
      "What is a requirements traceability matrix, and why is it important?",
      "What is a gap analysis?",
      "How do you facilitate a requirements workshop?",
      "Tell me about a time you identified a business problem that others had missed.",
      "How do you prioritize requirements?",
      "Case Study: A business department wants a new software system to 'improve efficiency'. How would you approach this request to define the actual requirements?"
    ]
  }

  // NOTE: You can continue adding more categories (UX Design, Cybersecurity, etc.)
  // by following the exact same structure above and copying questions from your
  // big master list.
};

export const QUESTION_CATEGORIES = Object.values(QUESTION_BANK).map(
  ({ key, title, description }) => ({ key, title, description })
);

export function getQuestionsForCategory(key) {
  return QUESTION_BANK[key]?.questions ?? [];
}
