import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GENERATIVE_AI_API_KEY);

export async function POST(request) {
  try {
    const {
      resume,
      jobDescription,
      previousAnswers = [],
      questionHistory = [],
      candidateSkills = [],
      interviewPhase = "initial", // initial, technical, behavioral, closing
      sessionId,
      candidateId,
    } = await request.json();

    if (!process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
      return Response.json(
        { error: "Gemini API key not configured" },
        { status: 500 }
      );
    }

    const model = genAI.getGenerativeModel({ model: "gemini-pro" });

    // Build context for AI interviewer
    const interviewContext = `
You are an expert technical interviewer. Generate the next interview question based on:

Resume Summary: ${resume}
Job Description: ${jobDescription}
Candidate Skills: ${candidateSkills.join(", ")}
Interview Phase: ${interviewPhase}
Previous Questions Asked: ${questionHistory.join("; ")}
${previousAnswers.length > 0 ? `Candidate's Previous Answers: ${previousAnswers[previousAnswers.length - 1]}` : ""}

Requirements:
1. Question should be relevant to job description
2. Build upon previous answers to assess depth of knowledge
3. Adjust difficulty based on candidate responses
4. For technical phase: Ask follow-up on specific claims in resume
5. For behavioral phase: Use STAR method approach
6. Make it adaptive - probe deeper if answers are vague

Generate ONLY ONE question. Format response as JSON with:
{
  "question": "Your question here",
  "type": "technical|behavioral|practical|followup",
  "difficulty": "easy|medium|hard",
  "expectedKeyPoints": ["point1", "point2"],
  "followUpOpportunities": ["followup1", "followup2"],
  "rationale": "Why this question in this phase"
}`;

    try {
      const result = await model.generateContent(interviewContext);
      const responseText = await result.response.text();

      // Parse JSON response
      let questionData;
      try {
        // Extract JSON from response
        const jsonMatch = responseText.match(/\{[\s\S]*\}/);
        questionData = JSON.parse(jsonMatch ? jsonMatch[0] : responseText);
      } catch {
        questionData = {
          question: responseText,
          type: "fallback",
          difficulty: "medium",
          expectedKeyPoints: [],
          followUpOpportunities: [],
          rationale: "Generated by Gemini",
        };
      }

      // Generate follow-up questions for depth
      const followUpPrompt = `Based on the previous question "${questionData.question}", generate 2 potential follow-up questions that could probe deeper into the candidate's knowledge:

Response format:
[
  {"question": "follow-up 1", "triggers": ["if answer mentions X", "if vague response"]},
  {"question": "follow-up 2", "triggers": ["if answer mentions Y", "if incomplete"]}
]`;

      let followUpQuestions = [];
      try {
        const followUpResult = await model.generateContent(followUpPrompt);
        const followUpText = await followUpResult.response.text();
        const jsonMatch = followUpText.match(/\[[\s\S]*\]/);
        followUpQuestions = JSON.parse(jsonMatch ? jsonMatch[0] : "[]");
      } catch {
        followUpQuestions = [];
      }

      const response = {
        sessionId,
        candidateId,
        timestamp: new Date().toISOString(),
        currentQuestion: {
          ...questionData,
          questionNumber: questionHistory.length + 1,
          phase: interviewPhase,
        },
        followUpQuestions,
        adaptiveInsights: {
          candidateStrengths: identifyStrengths(previousAnswers),
          gapAreas: identifyGaps(previousAnswers, candidateSkills),
          nextPhaseRecommendation: getNextPhase(interviewPhase, previousAnswers),
        },
      };

      return Response.json(response, { status: 200 });
    } catch (error) {
      console.error("Error generating question:", error);
      return Response.json(
        {
          error: "Failed to generate question",
          details: error.message,
          fallbackQuestion: generateFallbackQuestion(interviewPhase),
        },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error("Interview engine error:", error);
    return Response.json(
      { error: "Interview engine failed", details: error.message },
      { status: 500 }
    );
  }
}

function identifyStrengths(answers) {
  // Simple heuristic to identify strengths from answers
  const strengths = [];

  if (answers.length > 0) {
    const lastAnswer = answers[answers.length - 1];

    // Check for technical depth
    if (hasDepthIndicators(lastAnswer)) strengths.push("Technical Depth");

    // Check for clear communication
    if (hasClarityIndicators(lastAnswer)) strengths.push("Clear Communication");

    // Check for practical experience
    if (hasPracticalExperience(lastAnswer)) strengths.push("Practical Experience");

    // Check for problem-solving
    if (hasProblemSolvingApproach(lastAnswer))
      strengths.push("Problem-Solving Mindset");
  }

  return strengths;
}

function identifyGaps(answers, skills) {
  const gaps = [];

  const coveredAreas = new Set();
  answers.forEach((answer) => {
    skills.forEach((skill) => {
      if (answer.toLowerCase().includes(skill.toLowerCase())) {
        coveredAreas.add(skill);
      }
    });
  });

  skills.forEach((skill) => {
    if (!coveredAreas.has(skill)) {
      gaps.push(skill);
    }
  });

  return gaps;
}

function getNextPhase(currentPhase, answers) {
  const phaseFlow = ["initial", "technical", "behavioral", "closing"];
  const currentIndex = phaseFlow.indexOf(currentPhase);

  // If sufficient answers, move to next phase
  if (answers.length > 2 && currentIndex < phaseFlow.length - 1) {
    return phaseFlow[currentIndex + 1];
  }

  return currentPhase;
}

function hasDepthIndicators(answer) {
  const indicators = [
    /architecture|design pattern/i,
    /trade-off|trade off/i,
    /optimization|performance/i,
    /scalability/i,
    /database|sql|nosql/i,
  ];

  return indicators.some((indicator) => indicator.test(answer));
}

function hasClarityIndicators(answer) {
  // Check for structured answers
  return (
    /^(first|second|third|1\.|2\.|3\.)/im.test(answer) &&
    answer.split(/\n/).length > 2
  );
}

function hasPracticalExperience(answer) {
  return /built|implemented|deployed|used|worked with|experience/i.test(answer);
}

function hasProblemSolvingApproach(answer) {
  return /challenge|problem|solved|approach|solution|debug/i.test(answer);
}

function generateFallbackQuestion(phase) {
  const questions = {
    initial: {
      question:
        "Tell me about a project you're most proud of and why it matters to you.",
      type: "behavioral",
      difficulty: "easy",
    },
    technical: {
      question: "Walk me through how you'd architect a solution for a real-world problem you've faced.",
      type: "technical",
      difficulty: "medium",
    },
    behavioral: {
      question: "Describe a time when you had to learn something new quickly. How did you approach it?",
      type: "behavioral",
      difficulty: "medium",
    },
    closing: {
      question: "What questions do you have for me about the role or company?",
      type: "closing",
      difficulty: "easy",
    },
  };

  return questions[phase] || questions.technical;
}
